// Emit the generated TypeScript module (SPEC §3): a branded time type, plus a runtime
// registry describing every hypertable and continuous aggregate. The registry is shaped to
// be consumable by the client extension WITHOUT the generator (it matches the manual
// TimescaleConfig the client accepts), satisfying CLAUDE.md's resilience requirement.
import type { TimescaleSchema } from "./dmmf.js";
import type { FileMap } from "./emit-migrations.js";

const GENERATED_BANNER = "// AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.";

/** Build the generated type-module file map for a parsed schema. */
export function emitTypes(schema: TimescaleSchema): FileMap {
  const registry: Record<string, unknown> = {
    hypertables: [...schema.hypertables].sort((a, b) => a.table.localeCompare(b.table)),
    continuousAggregates: [...schema.continuousAggregates].sort((a, b) => a.name.localeCompare(b.name)),
  };
  // Only emit relationsByModel when there ARE related-model relations — keeps the registry (and its
  // snapshot) byte-identical for schemas without inter-model relations. Keys sorted for determinism.
  const relationModels = Object.keys(schema.relationsByModel).sort();
  if (relationModels.length > 0) {
    registry.relationsByModel = Object.fromEntries(relationModels.map((m) => [m, schema.relationsByModel[m]]));
  }

  const source = `${GENERATED_BANNER}

/**
 * Branded time type for hypertable partition columns. Range-bounded query helpers can require
 * this so callers can't forget the time bound (SPEC §3).
 */
export type HypertableTime = Date & { readonly __timescaleTime: unique symbol };

/** Runtime description of every hypertable and continuous aggregate in the schema. */
export const registry = ${serialize(registry)} as const;

/** The shape of {@link registry}, for typing the client extension. */
export type TimescaleRegistry = typeof registry;
`;

  return { "index.ts": source };
}

/** Serialize a config object to a TS object literal. JSON is valid TS here (quoted keys/strings). */
function serialize(value: unknown): string {
  return JSON.stringify(value, null, 2);
}
