// Emit reset-safe, EVOLUTION-safe migration files as a pure { relativePath -> content } map
// (no filesystem, no wall-clock timestamps), so output is deterministic and snapshot-testable.
//
// The append-only "versioned objects migrations" strategy:
//
//   00000000000000_timescaledb_extension            -> fixed name, sorts FIRST (constraint 1)
//   99999999999999_timescaledb_objects_v0001        -> sorts LAST, after Prisma's CREATE TABLEs
//   99999999999999_timescaledb_objects_v0002        -> appended when the desired state CHANGES
//   ...
//
// Why append-only: `prisma migrate deploy` filters pending migrations by NAME only, so
// rewriting one fixed-name migration in place meant objects added after the first deploy were
// silently never applied (deploy saw the name as already done), and `migrate dev` treated the
// rewrite as a modified applied migration and forced a reset. Instead, each state change emits
// a NEW migration that (a) re-asserts the full desired state with idempotent, EXISTENCE-GUARDED
// DDL (a DO block that skips when the target table no longer exists, so old snapshots replay
// cleanly after a later Prisma migration dropped a table), and (b) explicitly removes objects
// that were present in the previous state and are gone now (caggs dropped, policies removed).
//
// The previous state travels in a generator-owned state file next to the migrations
// (STATE_FILE); the caller (the generator binary) reads/writes it so this module stays pure.
// An unchanged schema emits NOTHING — regeneration is a byte-stable no-op.
//
// All ordering uses code-point comparison (never localeCompare): generated bytes must be
// identical across machines and locales, or two developers would produce spuriously different
// migrations for the same schema.
import type { TimescaleSchema } from "./dmmf.js";
import type { CaggConfig, HypertableConfig } from "../core/types.js";
import { createExtensionSql } from "../core/extension.js";
import { createHypertableSql } from "../core/hypertable.js";
import { createContinuousAggregateSql } from "../core/continuousAggregate.js";
import { createRetentionPolicySql } from "../core/retention.js";
import { createCompressionPolicySql } from "../core/compression.js";
import { createChunkSkippingSql } from "../core/chunkSkipping.js";
import { existenceGuard, qualifiedIdent, quoteLiteral, relationLiteral } from "../core/sql.js";

export const EXTENSION_MIGRATION = "00000000000000_timescaledb_extension";
/** Prefix shared by every objects migration; the version suffix keeps them ordered and unique. */
export const OBJECTS_MIGRATION_PREFIX = "99999999999999_timescaledb_objects";
/** The pre-v1 fixed-name objects migration. Left untouched if present (it is applied history);
 * new versioned migrations sort after it and take over from the current state. */
export const LEGACY_OBJECTS_MIGRATION = OBJECTS_MIGRATION_PREFIX;
/** Name of the generator's state file inside the migrations directory. */
export const STATE_FILE = ".prisma-extension-timescaledb.json";

export type FileMap = Record<string, string>;

/** The durable slice of a schema that migrations are derived from (relations affect types only). */
export interface ObjectsState {
  hypertables: readonly HypertableConfig[];
  continuousAggregates: readonly CaggConfig[];
}

/** Contents of the state file: the last emitted state and the migration sequence number. */
export interface GeneratorState {
  version: 1;
  sequence: number;
  state: ObjectsState;
}

export interface EmitResult {
  /** New files to write (empty when the state is unchanged). Never rewrites an existing migration. */
  files: FileMap;
  /** Updated state-file content to persist, or undefined when nothing changed. */
  nextState?: GeneratorState;
}

const GENERATED_BANNER = "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.";

/** Code-point string comparison — locale-independent, unlike localeCompare. */
function byCodePoint(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Identity key of a relation. Under multiSchema two relations can share a name across schemas. */
function qualify(schema: string | undefined, name: string): string {
  return schema ? `${schema}.${name}` : name;
}

/**
 * Order continuous aggregates so a hierarchical cagg's source cagg is emitted (created) before
 * it — a topological sort over the `source`-is-another-cagg dependency. Independent caggs keep
 * a stable code-point order for deterministic output; a dependency cycle throws.
 */
function orderCaggs(caggs: readonly CaggConfig[]): CaggConfig[] {
  const byKey = new Map(caggs.map((c) => [qualify(c.schema, c.name), c]));
  const sorted: CaggConfig[] = [];
  const done = new Set<string>();
  const onPath = new Set<string>();
  const visit = (c: CaggConfig): void => {
    const key = qualify(c.schema, c.name);
    if (done.has(key)) return;
    if (onPath.has(key)) {
      throw new Error(`Continuous aggregate dependency cycle detected at "${c.name}".`);
    }
    onPath.add(key);
    const parent = byKey.get(qualify(c.sourceSchema, c.source)); // a source that is itself a cagg
    if (parent) visit(parent);
    onPath.delete(key);
    done.add(key);
    sorted.push(c);
  };
  for (const c of [...caggs].sort((a, b) => byCodePoint(qualify(a.schema, a.name), qualify(b.schema, b.name)))) {
    visit(c);
  }
  return sorted;
}

/** Canonicalize a state for comparison: stable object-key and array order, no undefineds. */
function canonicalState(schema: TimescaleSchema): ObjectsState {
  const hypertables = [...schema.hypertables]
    .sort((a, b) => byCodePoint(qualify(a.schema, a.table), qualify(b.schema, b.table)))
    // Strip relations: they drive the runtime registry, not migrations — a relation-only
    // change must not spawn a new migration.
    .map(({ relations: _relations, ...rest }) => rest);
  const continuousAggregates = orderCaggs(schema.continuousAggregates);
  return { hypertables, continuousAggregates };
}

/** Deep-stable JSON: object keys sorted, so equality is structural. */
function stableStringify(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) => {
    if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      const rec = v as Record<string, unknown>;
      return Object.keys(rec)
        .sort(byCodePoint)
        .reduce<Record<string, unknown>>((acc, k) => {
          acc[k] = rec[k];
          return acc;
        }, {});
    }
    return v;
  });
}

/** Render the guarded, idempotent creates for the full desired state. */
function renderCreates(state: ObjectsState): string[] {
  const parts: string[] = [];
  for (const h of state.hypertables) {
    parts.push(`-- Hypertable: ${qualify(h.schema, h.table)}\n${createHypertableSql(h).guardedUp}`);
    if (h.retention) {
      const sql = createRetentionPolicySql({
        table: h.table,
        ...(h.schema !== undefined ? { schema: h.schema } : {}),
        dropAfter: h.retention.dropAfter,
      }).guardedUp;
      parts.push(`-- Retention policy: ${qualify(h.schema, h.table)}\n${sql}`);
    }
    if (h.compression) {
      const c = h.compression;
      const sql = createCompressionPolicySql({
        table: h.table,
        ...(h.schema !== undefined ? { schema: h.schema } : {}),
        after: c.after,
        ...(c.segmentBy ? { segmentBy: c.segmentBy } : {}),
        ...(c.orderBy ? { orderBy: c.orderBy } : {}),
      }).guardedUp;
      parts.push(`-- Compression (columnstore) policy: ${qualify(h.schema, h.table)}\n${sql}`);
    }
    if (h.chunkSkipping && h.chunkSkipping.length > 0) {
      // After compression: chunk skipping records its range stats when chunks compress.
      const sql = createChunkSkippingSql({
        table: h.table,
        ...(h.schema !== undefined ? { schema: h.schema } : {}),
        columns: h.chunkSkipping,
      }).guardedUp;
      parts.push(`-- Chunk skipping: ${qualify(h.schema, h.table)}\n${sql}`);
    }
  }
  for (const c of state.continuousAggregates) {
    parts.push(`-- Continuous aggregate: ${qualify(c.schema, c.name)}\n${createContinuousAggregateSql(c).guardedUp}`);
  }
  return parts;
}

/**
 * Render removals for objects present in `previous` but absent from `current`. Caggs are
 * dropped (children before parents — reverse topological order); removed retention /
 * compression / chunk-skipping configs have their policies removed when the table survives.
 * A hypertable annotation removed while its table remains cannot be undone (TimescaleDB has
 * no un-create_hypertable); that is surfaced as a WARNING comment instead of silence.
 */
function renderRemovals(previous: ObjectsState, current: ObjectsState): string[] {
  const parts: string[] = [];

  const currentCaggs = new Set(current.continuousAggregates.map((c) => qualify(c.schema, c.name)));
  // Reverse topological order so a dropped hierarchical child goes before its dropped parent.
  for (const c of [...orderCaggs(previous.continuousAggregates)].reverse()) {
    if (currentCaggs.has(qualify(c.schema, c.name))) continue;
    // Constraint 4: DROP MATERIALIZED VIEW, never DROP VIEW.
    parts.push(
      `-- Removed continuous aggregate: ${qualify(c.schema, c.name)}\nDROP MATERIALIZED VIEW IF EXISTS ${qualifiedIdent(c.name, c.schema)};`,
    );
  }

  const currentByKey = new Map(current.hypertables.map((h) => [qualify(h.schema, h.table), h]));
  for (const prev of previous.hypertables) {
    const key = qualify(prev.schema, prev.table);
    const cur = currentByKey.get(key);
    const rel = relationLiteral(prev.table, prev.schema);
    const guard = existenceGuard(rel);
    if (!cur) {
      // The whole hypertable annotation is gone. If the table was dropped too, there is
      // nothing to do (guards skip). If the table remains, conversion cannot be undone.
      parts.push(
        `-- Removed hypertable annotation: ${key}. TimescaleDB cannot convert a hypertable back\n-- to a plain table; if ${key} still exists it stays a hypertable. Its policies are removed.\nDO $$ BEGIN\n  ${guard}\n  PERFORM remove_retention_policy(${rel}, if_exists => TRUE);\n  CALL remove_columnstore_policy(${rel}, if_exists => TRUE);\nEND $$;`,
      );
      continue;
    }
    if (prev.retention && !cur.retention) {
      parts.push(
        `-- Removed retention policy: ${key}\nDO $$ BEGIN\n  ${guard}\n  PERFORM remove_retention_policy(${rel}, if_exists => TRUE);\nEND $$;`,
      );
    }
    if (prev.compression && !cur.compression) {
      // remove_columnstore_policy is a PROCEDURE (CALL); leaves the columnstore enabled —
      // disabling fails once any chunk is compressed (same rationale as the builder's down).
      parts.push(
        `-- Removed compression policy: ${key}\nDO $$ BEGIN\n  ${guard}\n  CALL remove_columnstore_policy(${rel}, if_exists => TRUE);\nEND $$;`,
      );
    }
    const curSkip = new Set(cur.chunkSkipping ?? []);
    const droppedSkip = (prev.chunkSkipping ?? []).filter((col) => !curSkip.has(col));
    if (droppedSkip.length > 0) {
      const disables = droppedSkip
        .map((col) => `  PERFORM disable_chunk_skipping(${rel}, ${quoteLiteral(col)}, if_not_exists => TRUE);`)
        .join("\n");
      parts.push(
        `-- Removed chunk skipping: ${key} (${droppedSkip.join(", ")})\nDO $$ BEGIN\n  ${guard}\n  SET LOCAL timescaledb.enable_chunk_skipping = on;\n${disables}\nEND $$;`,
      );
    }
  }

  return parts;
}

/** The versioned folder name for objects migration `sequence` (zero-padded, code-point sortable). */
export function objectsMigrationName(sequence: number): string {
  return `${OBJECTS_MIGRATION_PREFIX}_v${String(sequence).padStart(4, "0")}`;
}

/**
 * Build the migration files to ADD for a parsed schema, given the previously persisted state.
 *
 * - First run (no previous state) with timescale objects: the extension migration plus
 *   `..._v0001` holding the full state. A pre-v1 fixed-name objects migration, if present, is
 *   the caller's applied history — it is never touched; v0001 re-asserts everything on top
 *   (idempotent), and sorts after it by name.
 * - Unchanged state: `{ files: {} }` and no state write — regeneration is a no-op.
 * - Changed state: one new `..._v<n+1>` migration with guarded creates for the full new state
 *   plus explicit removals for objects that disappeared.
 * - No timescale objects and no previous state: nothing to emit.
 */
export function emitMigrations(schema: TimescaleSchema, previous?: GeneratorState): EmitResult {
  const state = canonicalState(schema);
  const empty = state.hypertables.length === 0 && state.continuousAggregates.length === 0;

  if (!previous && empty) return { files: {} };
  if (previous && stableStringify(previous.state) === stableStringify(state)) return { files: {} };

  const sequence = (previous?.sequence ?? 0) + 1;
  const files: FileMap = {};

  // The extension migration is fixed-name and content-stable; (re-)emitting it is a
  // byte-identical write, safe on every run.
  files[`${EXTENSION_MIGRATION}/migration.sql`] = `${GENERATED_BANNER}
-- TimescaleDB extension setup. Standalone & leading so it runs before any table or
-- hypertable DDL (CLAUDE.md constraint 1).
${createExtensionSql().up}
`;

  const creates = renderCreates(state);
  const removals = previous ? renderRemovals(previous.state, state) : [];
  const sections = [...removals, ...creates];

  files[`${objectsMigrationName(sequence)}/migration.sql`] = `${GENERATED_BANNER}
-- TimescaleDB objects, state v${sequence}. Sorts last so the tables Prisma created in its own
-- migrations already exist. Never rewritten: a schema change appends the next version instead.
-- Every block is idempotent and guarded (skips if its table was dropped later), so a full
-- \`migrate reset\` replay of v1..v${sequence} converges on exactly this state (constraint 3).

${sections.join("\n\n")}
`;

  return { files, nextState: { version: 1, sequence, state } };
}
