// Emit reset-safe, EVOLUTION-safe migration files as a pure { relativePath -> content } map
// (no filesystem, no wall-clock timestamps), so output is deterministic and snapshot-testable.
//
// The append-only "versioned objects migrations" strategy:
//
//   00000000000000_timescaledb_extension            -> fixed name, sorts FIRST (constraint 1)
//   99999999999999_timescaledb_objects_v0001        -> sorts LAST, after Prisma's CREATE TABLEs
//   99999999999999_timescaledb_objects_v0002        -> appended when the desired state CHANGES
//   ...
//
// Why append-only: `prisma migrate deploy` filters pending migrations by NAME only, so
// rewriting one fixed-name migration in place meant objects added after the first deploy were
// silently never applied (deploy saw the name as already done), and `migrate dev` treated the
// rewrite as a modified applied migration and forced a reset. Instead, each state change emits
// a NEW migration that (a) re-asserts the full desired state with idempotent, EXISTENCE-GUARDED
// DDL (a DO block that skips when the target table no longer exists, so old snapshots replay
// cleanly after a later Prisma migration dropped a table), and (b) explicitly removes objects
// that were present in the previous state and are gone now (caggs dropped, policies removed).
//
// The previous state travels in a generator-owned state file next to the migrations
// (STATE_FILE); the caller (the generator binary) reads/writes it so this module stays pure.
// An unchanged schema emits NOTHING — regeneration is a byte-stable no-op.
//
// All ordering uses code-point comparison (never localeCompare): generated bytes must be
// identical across machines and locales, or two developers would produce spuriously different
// migrations for the same schema.
import type { TimescaleSchema } from "./dmmf.js";
import type { CaggConfig, HypertableConfig } from "../core/types.js";
import { createExtensionSql } from "../core/extension.js";
import { createHypertableSql } from "../core/hypertable.js";
import { createContinuousAggregateSql } from "../core/continuousAggregate.js";
import { createRetentionPolicySql } from "../core/retention.js";
import { createCompressionPolicySql } from "../core/compression.js";
import { createChunkSkippingSql } from "../core/chunkSkipping.js";
import { qualifiedIdent, quoteLiteral, relationLiteral, timescaleDoBlock } from "../core/sql.js";

export const EXTENSION_MIGRATION = "00000000000000_timescaledb_extension";
/** Prefix shared by every objects migration; the version suffix keeps them ordered and unique. */
export const OBJECTS_MIGRATION_PREFIX = "99999999999999_timescaledb_objects";
/** The pre-v1 fixed-name objects migration. Left untouched if present (it is applied history);
 * new versioned migrations sort after it and take over from the current state. */
export const LEGACY_OBJECTS_MIGRATION = OBJECTS_MIGRATION_PREFIX;
/** Name of the generator's state file inside the migrations directory. */
export const STATE_FILE = ".prisma-extension-timescaledb.json";

export type FileMap = Record<string, string>;

/** The durable slice of a schema that migrations are derived from (relations affect types only). */
export interface ObjectsState {
  hypertables: readonly HypertableConfig[];
  continuousAggregates: readonly CaggConfig[];
}

/** The state-file format this release reads and writes. */
export const STATE_VERSION = 1;

/** Contents of the state file: the last emitted state and the migration sequence number. */
export interface GeneratorState {
  version: typeof STATE_VERSION;
  sequence: number;
  state: ObjectsState;
  /** The state the latest objects migration diffed against, so that migration can be rebuilt
   * if its folder disappears. Empty when nothing came before it (a first run, or a recovery
   * from a lost state file). Absent only in files written before this field existed. */
  previous?: ObjectsState;
}

const EMPTY_STATE: ObjectsState = { hypertables: [], continuousAggregates: [] };

/**
 * Thrown by emitMigrations when the latest objects migration is missing and the state file
 * predates the `previous` field, so the migration cannot be rebuilt. The caller adds the path.
 */
export class MissingMigrationError extends Error {
  constructor(readonly migration: string) {
    super(
      `${migration} is missing and the state file does not record the state before it, so the migration cannot be rebuilt. Restore the folder from version control, or delete the state file to re-assert the full state as a new version (objects that migration removed are not removed again).`,
    );
    this.name = "MissingMigrationError";
  }
}

/**
 * Thrown by parseGeneratorState for a state file whose `version` is above STATE_VERSION. Such a
 * file was written by a newer prisma-extension-timescaledb. Treating it as corrupt would emit a
 * full re-assert migration and rewrite the file in the old format, so the generator aborts.
 */
export class NewerStateFileError extends Error {
  constructor(readonly fileVersion: number) {
    super(
      `state file was written by a newer prisma-extension-timescaledb (state version ${fileVersion}; this release reads version ${STATE_VERSION}). Upgrade the package before running prisma generate.`,
    );
    this.name = "NewerStateFileError";
  }
}

export interface EmitResult {
  /** New files to write. Empty when the state is unchanged and the extension migration is
   * already on disk. Never rewrites an existing migration. */
  files: FileMap;
  /** Updated state-file content to persist, or undefined when nothing changed. */
  nextState?: GeneratorState;
  /** Things the caller should print: consequences of this migration that run without error
   * but cost something, such as materialized data that cannot be rebuilt. Set only when
   * there is at least one. */
  warnings?: string[];
}

const GENERATED_BANNER = "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.";

/** Code-point string comparison — locale-independent, unlike localeCompare. */
function byCodePoint(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Identity key of a relation. Under multiSchema two relations can share a name across schemas. */
function qualify(schema: string | undefined, name: string): string {
  return schema ? `${schema}.${name}` : name;
}

/**
 * Order continuous aggregates so a hierarchical cagg's source cagg is emitted (created) before
 * it — a topological sort over the `source`-is-another-cagg dependency. Independent caggs keep
 * a stable code-point order for deterministic output; a dependency cycle throws.
 */
function orderCaggs(caggs: readonly CaggConfig[]): CaggConfig[] {
  const byKey = new Map(caggs.map((c) => [qualify(c.schema, c.name), c]));
  const sorted: CaggConfig[] = [];
  const done = new Set<string>();
  const onPath = new Set<string>();
  const visit = (c: CaggConfig): void => {
    const key = qualify(c.schema, c.name);
    if (done.has(key)) return;
    if (onPath.has(key)) {
      throw new Error(`Continuous aggregate dependency cycle detected at "${c.name}".`);
    }
    onPath.add(key);
    const parent = byKey.get(qualify(c.sourceSchema, c.source)); // a source that is itself a cagg
    if (parent) visit(parent);
    onPath.delete(key);
    done.add(key);
    sorted.push(c);
  };
  for (const c of [...caggs].sort((a, b) => byCodePoint(qualify(a.schema, a.name), qualify(b.schema, b.name)))) {
    visit(c);
  }
  return sorted;
}

/**
 * Canonicalize a state for comparison: stable object-key and array order, no undefineds, and
 * ONLY the fields that reach emitted SQL. `relations`, `columns`, and `model` drive the runtime
 * registry, not migrations — a rename/@map-only change must not spawn a new (empty) migration.
 * Also applied to a PERSISTED previous state before diffing: a pre-versioning state file may
 * still carry the registry-only fields, which must not read as a change after an upgrade.
 */
function canonicalObjects(state: ObjectsState): ObjectsState {
  const hypertables = [...state.hypertables]
    .sort((a, b) => byCodePoint(qualify(a.schema, a.table), qualify(b.schema, b.table)))
    .map(({ relations: _relations, columns: _columns, model: _model, ...rest }) => rest);
  // An explicit materializedOnly: true is TimescaleDB's default, the same as leaving it out:
  // stored as absent so adding or removing the word never reads as a change.
  const continuousAggregates = orderCaggs(state.continuousAggregates).map(({ model: _model, materializedOnly, ...rest }) =>
    materializedOnly === false ? { ...rest, materializedOnly } : rest,
  );
  return { hypertables, continuousAggregates };
}

function canonicalState(schema: TimescaleSchema): ObjectsState {
  return canonicalObjects({ hypertables: schema.hypertables, continuousAggregates: schema.continuousAggregates });
}

/** A cagg's definition WITHOUT its refresh policy and materialized_only flag: what decides
 * drop-and-recreate. The policy is managed separately (it can be removed/re-added without
 * touching the materialized data), and materialized_only is an ALTER on the live view. */
function caggDefinition(c: CaggConfig): string {
  const { refresh: _refresh, materializedOnly: _materializedOnly, model: _model, ...definition } = c;
  return stableStringify(definition);
}

/** The hypertable at the bottom of a cagg's source chain (a cagg may be built on a cagg). */
function rootHypertable(state: ObjectsState, c: CaggConfig): HypertableConfig | undefined {
  const caggs = new Map(state.continuousAggregates.map((x) => [qualify(x.schema, x.name), x]));
  const hypertables = new Map(state.hypertables.map((h) => [qualify(h.schema, h.table), h]));
  const seen = new Set<string>();
  let source = qualify(c.sourceSchema, c.source);
  while (!hypertables.has(source)) {
    const parent = caggs.get(source);
    if (!parent || seen.has(source)) return undefined;
    seen.add(source);
    source = qualify(parent.sourceSchema, parent.source);
  }
  return hypertables.get(source);
}

/**
 * Turning multiSchema on (or off) changes every identity key from `Name` to `schema.Name`
 * without moving anything in the database. Diffed as-is, the old keys read as removed and the
 * new ones as added: every cagg dropped and recreated empty, every policy removed and re-added.
 * This rewrites the previous state's schema fields to the current ones wherever a relation of
 * the same bare name exists on exactly one side qualified, so the diff sees the same object.
 * A relation that really moved between two named schemas is left alone.
 */
function alignSchemaFlips(previous: ObjectsState, current: ObjectsState): { previous: ObjectsState; notes: string[] } {
  const notes: string[] = [];
  const flipped = (a: string | undefined, b: string | undefined): boolean => (a === undefined) !== (b === undefined);

  const prevHyperKeys = new Set(previous.hypertables.map((h) => qualify(h.schema, h.table)));
  const curHyperKeys = new Set(current.hypertables.map((h) => qualify(h.schema, h.table)));
  const hypertables = previous.hypertables.map((prev): HypertableConfig => {
    const key = qualify(prev.schema, prev.table);
    if (curHyperKeys.has(key)) return prev;
    const match = current.hypertables.find(
      (c) => c.table === prev.table && flipped(prev.schema, c.schema) && !prevHyperKeys.has(qualify(c.schema, c.table)),
    );
    if (!match) return prev;
    notes.push(`hypertable ${key} is now declared as ${qualify(match.schema, match.table)}: the same relation, nothing to drop or re-add.`);
    const { schema: _schema, ...rest } = prev;
    return match.schema === undefined ? rest : { ...rest, schema: match.schema };
  });

  const prevCaggKeys = new Set(previous.continuousAggregates.map((c) => qualify(c.schema, c.name)));
  const curCaggKeys = new Set(current.continuousAggregates.map((c) => qualify(c.schema, c.name)));
  const continuousAggregates = previous.continuousAggregates.map((prev): CaggConfig => {
    const key = qualify(prev.schema, prev.name);
    if (curCaggKeys.has(key)) return prev;
    const match = current.continuousAggregates.find(
      (c) => c.name === prev.name && flipped(prev.schema, c.schema) && !prevCaggKeys.has(qualify(c.schema, c.name)),
    );
    if (!match) return prev;
    notes.push(`continuous aggregate ${key} is now declared as ${qualify(match.schema, match.name)}: the same relation, nothing to drop.`);
    const { schema: _schema, sourceSchema: _sourceSchema, ...rest } = prev;
    return {
      ...rest,
      ...(match.schema !== undefined ? { schema: match.schema } : {}),
      ...(match.sourceSchema !== undefined ? { sourceSchema: match.sourceSchema } : {}),
    };
  });

  return { previous: { hypertables, continuousAggregates }, notes };
}

/**
 * Changes that no migration can apply to a live hypertable: the time column, the space
 * partition column, or a space dimension removed (TimescaleDB has no remove_dimension). The
 * idempotent create would run without error and change nothing, or add a second space
 * dimension, and the state file would then record the new value as done (issue #161). Better
 * to stop here, before anything is written.
 */
function assertHypertableChangesApplicable(previous: ObjectsState, current: ObjectsState): void {
  const currentByKey = new Map(current.hypertables.map((h) => [qualify(h.schema, h.table), h]));
  const advice =
    "TimescaleDB cannot apply this to a live hypertable. Revert the annotation, or declare the new layout on a new model (a new table), copy the data across, and drop the old model.";
  for (const prev of previous.hypertables) {
    const key = qualify(prev.schema, prev.table);
    const cur = currentByKey.get(key);
    if (!cur) continue;
    if (prev.column !== cur.column) {
      throw new Error(`Hypertable ${key}: the time column changed from "${prev.column}" to "${cur.column}". ${advice}`);
    }
    if (prev.spacePartition && !cur.spacePartition) {
      throw new Error(
        `Hypertable ${key}: the space dimension on "${prev.spacePartition.column}" was removed, and TimescaleDB has no way to remove a dimension. ${advice}`,
      );
    }
    if (prev.spacePartition && cur.spacePartition && prev.spacePartition.column !== cur.spacePartition.column) {
      throw new Error(
        `Hypertable ${key}: the space partition column changed from "${prev.spacePartition.column}" to "${cur.spacePartition.column}". ${advice}`,
      );
    }
  }
}

/** Deep-stable JSON: object keys sorted, so equality is structural. */
function stableStringify(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) => {
    if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      const rec = v as Record<string, unknown>;
      return Object.keys(rec)
        .sort(byCodePoint)
        .reduce<Record<string, unknown>>((acc, k) => {
          acc[k] = rec[k];
          return acc;
        }, {});
    }
    return v;
  });
}

/** Render the guarded, idempotent creates for the full desired state. */
function renderCreates(state: ObjectsState): string[] {
  const parts: string[] = [];
  for (const h of state.hypertables) {
    parts.push(`-- Hypertable: ${qualify(h.schema, h.table)}\n${createHypertableSql(h).guardedUp}`);
    if (h.retention) {
      const sql = createRetentionPolicySql({
        table: h.table,
        ...(h.schema !== undefined ? { schema: h.schema } : {}),
        dropAfter: h.retention.dropAfter,
      }).guardedUp;
      parts.push(`-- Retention policy: ${qualify(h.schema, h.table)}\n${sql}`);
    }
    if (h.compression) {
      const c = h.compression;
      const sql = createCompressionPolicySql({
        table: h.table,
        ...(h.schema !== undefined ? { schema: h.schema } : {}),
        after: c.after,
        ...(c.segmentBy ? { segmentBy: c.segmentBy } : {}),
        ...(c.orderBy ? { orderBy: c.orderBy } : {}),
      }).guardedUp;
      parts.push(`-- Compression (columnstore) policy: ${qualify(h.schema, h.table)}\n${sql}`);
    }
    if (h.chunkSkipping && h.chunkSkipping.length > 0) {
      // After compression: chunk skipping records its range stats when chunks compress.
      const sql = createChunkSkippingSql({
        table: h.table,
        ...(h.schema !== undefined ? { schema: h.schema } : {}),
        columns: h.chunkSkipping,
      }).guardedUp;
      parts.push(`-- Chunk skipping: ${qualify(h.schema, h.table)}\n${sql}`);
    }
  }
  for (const c of state.continuousAggregates) {
    parts.push(`-- Continuous aggregate: ${qualify(c.schema, c.name)}\n${createContinuousAggregateSql(c).guardedUp}`);
  }
  return parts;
}

/**
 * Render removals for objects present in `previous` but absent from `current`. Caggs are
 * dropped (children before parents — reverse topological order); removed retention /
 * compression / chunk-skipping configs have their policies removed when the table survives.
 * A hypertable annotation removed while its table remains cannot be undone (TimescaleDB has
 * no un-create_hypertable); that is surfaced as a WARNING comment instead of silence.
 */
function renderRemovals(previous: ObjectsState, current: ObjectsState, warnings: string[]): string[] {
  const parts: string[] = [];

  const currentCaggByKey = new Map(current.continuousAggregates.map((c) => [qualify(c.schema, c.name), c]));
  const prevCaggByKey = new Map(previous.continuousAggregates.map((c) => [qualify(c.schema, c.name), c]));

  // Caggs to DROP: removed ones, CHANGED ones (CREATE ... IF NOT EXISTS would silently keep the
  // old definition), and — transitively — every cagg whose source chain reaches a dropped one
  // (a matview cannot outlive its source). Dropped-but-still-declared caggs are recreated by
  // renderCreates in the same migration; their materialized data refills via policy/refresh.
  const dropSet = new Set<string>();
  for (const [key, prev] of prevCaggByKey) {
    const cur = currentCaggByKey.get(key);
    if (!cur) dropSet.add(key); // removed
    else if (caggDefinition(prev) !== caggDefinition(cur)) dropSet.add(key); // changed
  }
  // Transitive dependents, over the union graph (a child may exist in either state).
  const unionCaggs = new Map(prevCaggByKey);
  for (const [key, c] of currentCaggByKey) if (!unionCaggs.has(key)) unionCaggs.set(key, c);
  let grew = true;
  while (grew) {
    grew = false;
    for (const [key, c] of unionCaggs) {
      if (dropSet.has(key)) continue;
      if (dropSet.has(qualify(c.sourceSchema, c.source))) {
        dropSet.add(key);
        grew = true;
      }
    }
  }
  // Reverse topological order so a dependent child is dropped before its parent.
  for (const c of [...orderCaggs([...unionCaggs.values()])].reverse()) {
    const key = qualify(c.schema, c.name);
    if (!dropSet.has(key)) continue;
    let reason = !currentCaggByKey.has(key) ? "Removed" : "Changed (drop + recreate; materialized data refills on refresh)";
    // The refill only reaches rows the source still holds. Under a retention policy every
    // bucket older than the window is gone for good, which deserves more than a comment.
    const cur = currentCaggByKey.get(key);
    const root = cur ? rootHypertable(current, cur) : undefined;
    if (cur && root?.retention) {
      const rootKey = qualify(root.schema, root.table);
      reason = `Changed (drop + recreate). WARNING: source ${rootKey} drops rows after ${root.retention.dropAfter}; buckets older than that are lost`;
      warnings.push(
        `continuous aggregate ${key} is dropped and recreated because its definition changed, and its source ${rootKey} drops rows after ${root.retention.dropAfter}: buckets older than that cannot be rebuilt and are lost.`,
      );
    }
    // Constraint 4: DROP MATERIALIZED VIEW, never DROP VIEW.
    parts.push(`-- ${reason} continuous aggregate: ${key}\nDROP MATERIALIZED VIEW IF EXISTS ${qualifiedIdent(c.name, c.schema)};`);
  }

  // Surviving, unchanged caggs whose REFRESH POLICY changed or disappeared: the guarded create
  // re-adds with if_not_exists, which keeps old parameters — remove the old policy first.
  // (remove_continuous_aggregate_policy's idempotent flag is confusingly named if_not_exists.)
  for (const [key, prev] of prevCaggByKey) {
    if (dropSet.has(key)) continue;
    const cur = currentCaggByKey.get(key);
    if (!cur) continue;
    const rel = relationLiteral(cur.name, cur.schema);
    // materialized_only is an ALTER on the live view, never a reason to drop it (the default,
    // an omitted flag, is true on the TimescaleDB versions this package supports).
    if ((prev.materializedOnly ?? true) !== (cur.materializedOnly ?? true)) {
      parts.push(
        `-- Changed materialized_only: ${key}\n${timescaleDoBlock(`  ALTER MATERIALIZED VIEW ${qualifiedIdent(cur.name, cur.schema)} SET (timescaledb.materialized_only = ${cur.materializedOnly ?? true});`, rel)}`,
      );
    }
    if (!prev.refresh) continue;
    if (cur.refresh && stableStringify(prev.refresh) === stableStringify(cur.refresh)) continue;
    parts.push(
      `-- ${cur.refresh ? "Changed" : "Removed"} refresh policy: ${key}\n${timescaleDoBlock(`  PERFORM remove_continuous_aggregate_policy(${rel}, if_not_exists => TRUE);`, rel)}`,
    );
  }

  const currentByKey = new Map(current.hypertables.map((h) => [qualify(h.schema, h.table), h]));
  for (const prev of previous.hypertables) {
    const key = qualify(prev.schema, prev.table);
    const cur = currentByKey.get(key);
    const rel = relationLiteral(prev.table, prev.schema);
    if (!cur) {
      // The whole hypertable annotation is gone. If the table was dropped too, there is
      // nothing to do (guards skip). If the table remains, conversion cannot be undone.
      parts.push(
        `-- Removed hypertable annotation: ${key}. TimescaleDB cannot convert a hypertable back\n-- to a plain table; if ${key} still exists it stays a hypertable. Its policies are removed.\n${timescaleDoBlock(`  PERFORM remove_retention_policy(${rel}, if_exists => TRUE);\n  CALL remove_columnstore_policy(${rel}, if_exists => TRUE);`, rel)}`,
      );
      continue;
    }
    // A policy REMOVED or CHANGED both need the old one removed first: TimescaleDB never
    // updates an existing policy whose parameters differ (if_not_exists keeps the old one with
    // a NOTICE), so the guarded re-add in renderCreates only works on a clean slate.
    if (prev.retention && (!cur.retention || stableStringify(prev.retention) !== stableStringify(cur.retention))) {
      parts.push(
        `-- ${cur.retention ? "Changed" : "Removed"} retention policy: ${key}\n${timescaleDoBlock(`  PERFORM remove_retention_policy(${rel}, if_exists => TRUE);`, rel)}`,
      );
    }
    if (prev.compression && (!cur.compression || stableStringify(prev.compression) !== stableStringify(cur.compression))) {
      // remove_columnstore_policy is a PROCEDURE (CALL); leaves the columnstore enabled —
      // disabling fails once any chunk is compressed (same rationale as the builder's down).
      // A segmentby or orderby that disappeared is RESET here: the re-add only SETs the options
      // still declared, so without this the table would keep segmenting by the old column.
      const gone: string[] = [];
      if (prev.compression.segmentBy?.length && !cur.compression?.segmentBy?.length) gone.push("timescaledb.segmentby");
      if (prev.compression.orderBy?.length && !cur.compression?.orderBy?.length) gone.push("timescaledb.orderby");
      const resets = gone.map((opt) => `\n  ALTER TABLE ${qualifiedIdent(prev.table, prev.schema)} RESET (${opt});`).join("");
      parts.push(
        `-- ${cur.compression ? "Changed" : "Removed"} compression policy: ${key}\n${timescaleDoBlock(`  CALL remove_columnstore_policy(${rel}, if_exists => TRUE);${resets}`, rel)}`,
      );
    }
    const curSkip = new Set(cur.chunkSkipping ?? []);
    const droppedSkip = (prev.chunkSkipping ?? []).filter((col) => !curSkip.has(col));
    if (droppedSkip.length > 0) {
      const disables = droppedSkip
        .map((col) => `  PERFORM disable_chunk_skipping(${rel}, ${quoteLiteral(col)}, if_not_exists => TRUE);`)
        .join("\n");
      parts.push(
        `-- Removed chunk skipping: ${key} (${droppedSkip.join(", ")})\n${timescaleDoBlock(`  SET LOCAL timescaledb.enable_chunk_skipping = on;\n${disables}`, rel)}`,
      );
    }
  }

  return parts;
}

/** The versioned folder name for objects migration `sequence` (zero-padded, code-point sortable). */
export function objectsMigrationName(sequence: number): string {
  return `${OBJECTS_MIGRATION_PREFIX}_v${String(sequence).padStart(4, "0")}`;
}

/**
 * Parse and validate a state-file's raw JSON. Returns undefined for anything that is not a
 * fully-shaped v1 state. A hand-edited file with a missing array would otherwise surface
 * later as a TypeError deep inside the removal diff. The one exception throws: a `version`
 * that is an integer above STATE_VERSION is a newer release's file, not a corrupt one, and
 * the caller must abort rather than overwrite it (NewerStateFileError).
 */
export function parseGeneratorState(raw: string | undefined): GeneratorState | undefined {
  if (raw === undefined) return undefined;
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch {
    return undefined;
  }
  if (json === null || typeof json !== "object") return undefined;
  const version = (json as Record<string, unknown>)["version"];
  if (typeof version === "number" && Number.isInteger(version) && version > STATE_VERSION) {
    throw new NewerStateFileError(version);
  }
  const parsed = json as Partial<GeneratorState>;
  if (
    parsed.version === STATE_VERSION &&
    Number.isInteger(parsed.sequence) &&
    (parsed.sequence as number) >= 1 &&
    isObjectsState(parsed.state) &&
    (parsed.previous === undefined || isObjectsState(parsed.previous))
  ) {
    return parsed as GeneratorState;
  }
  return undefined;
}

/** Entry-level shape check: the removal diff reads these fields directly, so a null or
 * truncated entry must fall back to full re-assert, not throw mid-diff. */
function isObjectsState(value: unknown): value is ObjectsState {
  if (value === null || typeof value !== "object") return false;
  const { hypertables, continuousAggregates } = value as Partial<ObjectsState>;
  return (
    Array.isArray(hypertables) &&
    Array.isArray(continuousAggregates) &&
    hypertables.every(
      (h: unknown) =>
        h !== null &&
        typeof h === "object" &&
        typeof (h as Partial<HypertableConfig>).table === "string" &&
        typeof (h as Partial<HypertableConfig>).column === "string",
    ) &&
    continuousAggregates.every(
      (c: unknown) =>
        c !== null &&
        typeof c === "object" &&
        typeof (c as Partial<CaggConfig>).name === "string" &&
        typeof (c as Partial<CaggConfig>).source === "string" &&
        Array.isArray((c as Partial<CaggConfig>).aggregates),
    )
  );
}

/** The highest existing `..._v000N` sequence among migration folder names (0 when none). */
export function maxObjectsSequence(folderNames: readonly string[]): number {
  const pattern = new RegExp(`^${OBJECTS_MIGRATION_PREFIX}_v(\\d{4,})$`);
  let max = 0;
  for (const name of folderNames) {
    const m = pattern.exec(name);
    if (m) max = Math.max(max, Number(m[1]));
  }
  return max;
}

/**
 * Build the migration files to ADD for a parsed schema, given the previously persisted state.
 *
 * - First run (no previous state) with timescale objects: the extension migration plus
 *   `..._v0001` holding the full state. A pre-v1 fixed-name objects migration, if present, is
 *   the caller's applied history — it is never touched; v0001 re-asserts everything on top
 *   (idempotent), and sorts after it by name.
 * - Unchanged state: `{ files: {} }` and no state write — regeneration is a no-op.
 * - Changed state: one new `..._v<n+1>` migration with guarded creates for the full new state
 *   plus explicit removals for objects that disappeared.
 * - No timescale objects and no previous state: nothing to emit.
 *
 * `maxExistingSequence` is the highest `..._v000N` folder already on disk (0 when none): the
 * next sequence never collides with it, so a lost or corrupt state file can never overwrite an
 * applied versioned migration — recovery emits the FULL state as the next version instead.
 *
 * `extensionMigrationExists` says whether `00000000000000_timescaledb_extension` is already on
 * disk. It is emitted only when absent: it is applied history, and rewriting it would change
 * the checksum Prisma recorded for it. A missing one is re-emitted even when nothing else
 * changed, so deleting the folder heals on the next generate.
 *
 * `latestObjectsMigrationExists` says whether the folder for `previous.sequence` is still on
 * disk (ignored without a previous state). When it is gone, the recorded state has no
 * migration behind it, so the next version rebuilds it: the diff runs from the state the lost
 * migration itself diffed against (`previous.previous`), which brings back its removals and
 * drop-and-recreates, and covers any schema change made since. A state file that predates the
 * `previous` field cannot rebuild a lost migration beyond v0001 and throws instead
 * (MissingMigrationError), because a healed version without those removals would leave old
 * objects in place silently.
 */
export function emitMigrations(
  schema: TimescaleSchema,
  previous?: GeneratorState,
  maxExistingSequence = 0,
  extensionMigrationExists = false,
  latestObjectsMigrationExists = true,
): EmitResult {
  const state = canonicalState(schema);
  const empty = state.hypertables.length === 0 && state.continuousAggregates.length === 0;

  // The state file names the latest objects migration; when that folder is gone, the recorded
  // state has nothing behind it (an undeployed migration a developer deleted to redo it, or a
  // folder lost in a merge). Decided before the unchanged-state return below: an unchanged
  // schema is exactly the case that would otherwise emit nothing forever.
  const latestMissing = previous !== undefined && !latestObjectsMigrationExists;
  if (latestMissing && previous.sequence > 1 && previous.previous === undefined) {
    throw new MissingMigrationError(objectsMigrationName(previous.sequence));
  }

  // Canonicalize the persisted state too: a pre-versioning state file may carry the
  // registry-only fields the canonical form strips, and that must not read as a change.
  // While healing, the base is the state the lost migration diffed against, so the rebuilt
  // version carries the same removals. For a lost v0001 nothing came before it.
  const rawPrevState = latestMissing
    ? previous.previous && canonicalObjects(previous.previous)
    : previous && canonicalObjects(previous.state);
  // A multiSchema flip re-qualifies every key without moving anything; diff against the
  // previous state re-qualified the same way, so the same object never reads as dropped.
  const aligned = rawPrevState ? alignSchemaFlips(rawPrevState, state) : undefined;
  const prevState = aligned?.previous;
  const flipNotes = aligned?.notes ?? [];
  // The base the emitted migration diffs against, recorded so it can be rebuilt if lost. It is
  // the empty state, never absent, when there was nothing before: an absent field means only
  // "written by an older release", which is what the throw above keys on.
  const base = prevState ?? EMPTY_STATE;

  // The extension migration is fixed-name, and once it exists on disk it is applied history:
  // rewriting it would change its checksum and make `migrate dev` reject it as "modified after
  // it was applied". Emit it only when it is absent, so a package upgrade that improves the
  // extension SQL reaches new projects without breaking existing ones.
  //
  // This is decided BEFORE the unchanged-state returns below. A project whose objects have not
  // changed still needs the extension migration if the folder is missing (deleted by hand, lost
  // in a merge, or half-removed during a recovery), and without it every objects migration fails
  // on a fresh database. An empty schema declares no timescale objects at all, so it gets none.
  const files: FileMap = {};
  if (!extensionMigrationExists && !empty) {
    files[`${EXTENSION_MIGRATION}/migration.sql`] = `${GENERATED_BANNER}
-- TimescaleDB extension setup. Standalone & leading so it runs before any table or
-- hypertable DDL (CLAUDE.md constraint 1).
${createExtensionSql().up}
`;
  }

  const noHistory = !previous && maxExistingSequence === 0;
  if (noHistory && empty) return { files };
  if (prevState && !latestMissing && stableStringify(prevState) === stableStringify(state)) {
    // Only the qualification changed: nothing to migrate, but the state file must carry the new
    // keys or the next run would align again for nothing. Same sequence, same migration.
    if (flipNotes.length > 0 && previous) return { files, nextState: { ...previous, state } };
    return { files };
  }
  // State file lost but versioned migrations exist, and the schema is empty: without the
  // previous state there is nothing to diff removals against; emit nothing rather than a
  // migration of pure guesses. (The normal empty case with intact state emits removals.)
  if (!previous && empty) return { files };

  const sequence = Math.max(previous?.sequence ?? 0, maxExistingSequence) + 1;

  if (prevState) assertHypertableChangesApplicable(prevState, state);

  const warnings: string[] = [];
  const creates = renderCreates(state);
  const removals = prevState ? renderRemovals(prevState, state, warnings) : [];
  const notes = flipNotes.map((n) => `-- Schema qualification changed: ${n}`);
  const sections = [...notes, ...removals, ...creates];
  // Only reachable while healing: an empty state whose lost migration also had nothing before
  // it. An empty migration would just record a version that does nothing.
  if (sections.length === 0) return { files };

  files[`${objectsMigrationName(sequence)}/migration.sql`] = `${GENERATED_BANNER}
-- TimescaleDB objects, state v${sequence}. Sorts last so the tables Prisma created in its own
-- migrations already exist. Never rewritten: a schema change appends the next version instead.
-- Every block is idempotent and guarded (skips if its table was dropped later), so a full
-- \`migrate reset\` replay of v1..v${sequence} converges on exactly this state (constraint 3).

${sections.join("\n\n")}
`;

  return {
    files,
    nextState: { version: STATE_VERSION, sequence, state, previous: base },
    ...(warnings.length > 0 ? { warnings } : {}),
  };
}
