// Emit reset-safe migration files as a pure { relativePath -> content } map (no filesystem,
// no timestamps), so output is deterministic and trivially snapshot-testable.
//
// Two fixed-name migrations (the "managed migrations" strategy):
//   00000000000000_timescaledb_extension  -> sorts FIRST  (CREATE EXTENSION, constraint 1)
//   99999999999999_timescaledb_objects     -> sorts LAST   (after Prisma's CREATE TABLEs)
// Within the objects migration: all hypertable conversions first, then continuous aggregates
// (a cagg requires its source to already be a hypertable).
import type { TimescaleSchema } from "./dmmf.js";
import { createExtensionSql } from "../core/extension.js";
import { createHypertableSql } from "../core/hypertable.js";
import { createContinuousAggregateSql } from "../core/continuousAggregate.js";

export const EXTENSION_MIGRATION = "00000000000000_timescaledb_extension";
export const OBJECTS_MIGRATION = "99999999999999_timescaledb_objects";

export type FileMap = Record<string, string>;

const GENERATED_BANNER = "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.";

/** Build the reset-safe migration file map for a parsed schema. Empty if no timescale objects. */
export function emitMigrations(schema: TimescaleSchema): FileMap {
  const hypertables = [...schema.hypertables].sort((a, b) => a.table.localeCompare(b.table));
  const caggs = [...schema.continuousAggregates].sort((a, b) => a.name.localeCompare(b.name));

  if (hypertables.length === 0 && caggs.length === 0) return {};

  const files: FileMap = {};

  files[`${EXTENSION_MIGRATION}/migration.sql`] = `${GENERATED_BANNER}
-- TimescaleDB extension setup. Standalone & leading so it runs before any table or
-- hypertable DDL (CLAUDE.md constraint 1).
${createExtensionSql().up}
`;

  const parts: string[] = [];
  for (const h of hypertables) {
    parts.push(`-- Hypertable: ${h.table}\n${createHypertableSql(h).up}`);
  }
  for (const c of caggs) {
    parts.push(`-- Continuous aggregate: ${c.name}\n${createContinuousAggregateSql(c).up}`);
  }

  files[`${OBJECTS_MIGRATION}/migration.sql`] = `${GENERATED_BANNER}
-- Hypertable conversions and continuous aggregates. Sorts last so the tables Prisma
-- created in its own migrations already exist. All DDL is idempotent (constraint 3).

${parts.join("\n\n")}
`;

  return files;
}
