import { getDMMF } from "@prisma/internals";
import ts from "typescript";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { extractTimescaleSchema, type TimescaleSchema } from "../../src/generator/dmmf.js";
import { emitMigrations, EXTENSION_MIGRATION, OBJECTS_MIGRATION } from "../../src/generator/emit-migrations.js";
import { emitTypes } from "../../src/generator/emit-types.js";

const SCHEMA = `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}

/// @timescale.hypertable(column: "time", chunkInterval: "1 day")
model SensorReading {
  time        DateTime
  deviceId    Int
  temperature Float
  @@id([deviceId, time])
}

/// @timescale.continuousAggregate(source: "SensorReading", bucket: "1 hour", timeColumn: "time", refresh: { startOffset: "1 month", endOffset: "1 hour", scheduleInterval: "1 hour" })
view SensorHourly {
  bucket   DateTime /// @timescale.bucket
  deviceId Int      /// @timescale.groupBy
  avgTemp  Float    /// @timescale.aggregate(fn: "avg", column: "temperature")
  maxTemp  Float    /// @timescale.aggregate(fn: "max", column: "temperature")
  @@unique([deviceId, bucket])
}
`;

async function loadSchema(): Promise<TimescaleSchema> {
  return extractTimescaleSchema(await getDMMF({ datamodel: SCHEMA }));
}

/** Full strict type-check of a generated TS source string; returns diagnostic messages. */
function typeCheck(source: string): string[] {
  const dir = mkdtempSync(join(tmpdir(), "ts-emit-"));
  const file = join(dir, "generated.ts");
  writeFileSync(file, source, "utf8");
  const program = ts.createProgram([file], {
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
  });
  return ts.getPreEmitDiagnostics(program).map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"));
}

describe("emitMigrations", () => {
  it("emits an empty map when there are no timescale objects", () => {
    expect(emitMigrations({ hypertables: [], continuousAggregates: [] })).toEqual({});
  });

  it("emits the extension migration first and the objects migration last", async () => {
    const files = emitMigrations(await loadSchema());
    expect(Object.keys(files).sort()).toEqual([
      `${EXTENSION_MIGRATION}/migration.sql`,
      `${OBJECTS_MIGRATION}/migration.sql`,
    ]);
    // Folder names guarantee deploy order: 0000… sorts before any real timestamp; 9999… after.
    expect(EXTENSION_MIGRATION < "20260101000000_x").toBe(true);
    expect(OBJECTS_MIGRATION > "20260101000000_x").toBe(true);
  });

  it("matches the reset-safe extension SQL", async () => {
    const files = emitMigrations(await loadSchema());
    expect(files[`${EXTENSION_MIGRATION}/migration.sql`]).toMatchInlineSnapshot(`
      "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.
      -- TimescaleDB extension setup. Standalone & leading so it runs before any table or
      -- hypertable DDL (CLAUDE.md constraint 1).
      CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
      "
    `);
  });

  it("matches the reset-safe objects SQL (hypertable then cagg, no casts)", async () => {
    const files = emitMigrations(await loadSchema());
    const objects = files[`${OBJECTS_MIGRATION}/migration.sql`]!;
    expect(objects).not.toContain("::regclass");
    expect(objects).not.toContain("::name");
    expect(objects.indexOf("create_hypertable")).toBeLessThan(objects.indexOf("CREATE MATERIALIZED VIEW"));
    expect(objects).toMatchInlineSnapshot(`
      "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.
      -- Hypertable conversions and continuous aggregates. Sorts last so the tables Prisma
      -- created in its own migrations already exist. All DDL is idempotent (constraint 3).

      -- Hypertable: SensorReading
      SELECT create_hypertable(
        '"SensorReading"',
        by_range('time', INTERVAL '1 day'),
        if_not_exists => TRUE,
        migrate_data  => TRUE
      );

      -- Continuous aggregate: SensorHourly
      CREATE MATERIALIZED VIEW IF NOT EXISTS "SensorHourly"
        WITH (timescaledb.continuous) AS
      SELECT
        time_bucket('1 hour', "time") AS "bucket",
        "deviceId" AS "deviceId",
        avg("temperature") AS "avgTemp",
        max("temperature") AS "maxTemp"
      FROM "SensorReading"
      GROUP BY "bucket", "deviceId"
      WITH NO DATA;

      SELECT add_continuous_aggregate_policy('"SensorHourly"',
        start_offset      => INTERVAL '1 month',
        end_offset        => INTERVAL '1 hour',
        schedule_interval => INTERVAL '1 hour',
        if_not_exists     => TRUE
      );
      "
    `);
  });

  it("emits the retention policy after its hypertable when @timescale.retention is set", async () => {
    const dmmf = await getDMMF({
      datamodel: `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}

/// @timescale.hypertable(column: "time", chunkInterval: "1 day")
/// @timescale.retention(dropAfter: "30 days")
model SensorReading {
  time     DateTime
  deviceId Int
  @@id([deviceId, time])
}
`,
    });
    const objects = emitMigrations(extractTimescaleSchema(dmmf))[`${OBJECTS_MIGRATION}/migration.sql`]!;
    expect(objects).toContain(
      `SELECT add_retention_policy('"SensorReading"', drop_after => INTERVAL '30 days', if_not_exists => TRUE);`,
    );
    expect(objects).not.toContain("::regclass");
    // Retention is emitted after the create_hypertable it depends on.
    expect(objects.indexOf("create_hypertable")).toBeLessThan(objects.indexOf("add_retention_policy"));
  });
});

describe("emitTypes", () => {
  it("emits a type module that type-checks under strict mode", async () => {
    const source = emitTypes(await loadSchema())["index.ts"]!;
    expect(typeCheck(source)).toEqual([]);
  });

  it("matches the generated type module", async () => {
    const source = emitTypes(await loadSchema())["index.ts"]!;
    expect(source).toMatchInlineSnapshot(`
      "// AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.

      /**
       * Branded time type for hypertable partition columns. Range-bounded query helpers can require
       * this so callers can't forget the time bound (SPEC §3).
       */
      export type HypertableTime = Date & { readonly __timescaleTime: unique symbol };

      /** Runtime description of every hypertable and continuous aggregate in the schema. */
      export const registry = {
        "hypertables": [
          {
            "table": "SensorReading",
            "column": "time",
            "chunkInterval": "1 day"
          }
        ],
        "continuousAggregates": [
          {
            "name": "SensorHourly",
            "source": "SensorReading",
            "bucket": "1 hour",
            "timeColumn": "time",
            "bucketColumn": "bucket",
            "groupBy": [
              {
                "source": "deviceId",
                "output": "deviceId"
              }
            ],
            "aggregates": [
              {
                "name": "avgTemp",
                "fn": "avg",
                "column": "temperature"
              },
              {
                "name": "maxTemp",
                "fn": "max",
                "column": "temperature"
              }
            ],
            "refresh": {
              "startOffset": "1 month",
              "endOffset": "1 hour",
              "scheduleInterval": "1 hour"
            }
          }
        ]
      } as const;

      /** The shape of {@link registry}, for typing the client extension. */
      export type TimescaleRegistry = typeof registry;
      "
    `);
  });
});
