import { getDMMF } from "@prisma/internals";
import ts from "typescript";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { extractTimescaleSchema, type TimescaleSchema } from "../../src/generator/dmmf.js";
import {
  emitMigrations,
  objectsMigrationName,
  EXTENSION_MIGRATION,
  OBJECTS_MIGRATION_PREFIX,
  type GeneratorState,
} from "../../src/generator/emit-migrations.js";
import { emitTypes } from "../../src/generator/emit-types.js";

const SCHEMA = `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}

/// @timescale.hypertable(column: "time", chunkInterval: "1 day")
model SensorReading {
  time        DateTime
  deviceId    Int
  temperature Float
  @@id([deviceId, time])
}

/// @timescale.continuousAggregate(source: "SensorReading", bucket: "1 hour", timeColumn: "time", refresh: { startOffset: "1 month", endOffset: "1 hour", scheduleInterval: "1 hour" })
view SensorHourly {
  bucket   DateTime /// @timescale.bucket
  deviceId Int      /// @timescale.groupBy
  avgTemp  Float    /// @timescale.aggregate(fn: "avg", column: "temperature")
  maxTemp  Float    /// @timescale.aggregate(fn: "max", column: "temperature")
  @@unique([deviceId, bucket])
}
`;

async function loadSchema(): Promise<TimescaleSchema> {
  return extractTimescaleSchema(await getDMMF({ datamodel: SCHEMA }));
}

/** Full strict type-check of a generated TS source string; returns diagnostic messages. */
function typeCheck(source: string): string[] {
  const dir = mkdtempSync(join(tmpdir(), "ts-emit-"));
  const file = join(dir, "generated.ts");
  writeFileSync(file, source, "utf8");
  const program = ts.createProgram([file], {
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
  });
  return ts.getPreEmitDiagnostics(program).map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"));
}

describe("emitMigrations (append-only versioned objects migrations)", () => {
  const V1 = `${objectsMigrationName(1)}/migration.sql`;
  const V2 = `${objectsMigrationName(2)}/migration.sql`;

  it("emits nothing when there are no timescale objects and no history", () => {
    expect(emitMigrations({ hypertables: [], continuousAggregates: [], relationsByModel: {} })).toEqual({ files: {} });
  });

  it("first run: emits the extension migration and objects v0001, plus the state to persist", async () => {
    const { files, nextState } = emitMigrations(await loadSchema());
    expect(Object.keys(files).sort()).toEqual([`${EXTENSION_MIGRATION}/migration.sql`, V1]);
    // Folder names guarantee deploy order: 0000… sorts before any real timestamp; 9999… after.
    expect(EXTENSION_MIGRATION < "20260101000000_x").toBe(true);
    expect(objectsMigrationName(1) > "20260101000000_x").toBe(true);
    // Versions order lexicographically, and after the pre-v1 fixed-name migration.
    expect(objectsMigrationName(2) > objectsMigrationName(1)).toBe(true);
    expect(objectsMigrationName(1) > OBJECTS_MIGRATION_PREFIX).toBe(true);
    expect(objectsMigrationName(10) > objectsMigrationName(9)).toBe(true); // zero-padding
    expect(nextState?.sequence).toBe(1);
  });

  it("unchanged schema: regeneration is a no-op (no files, no state write)", async () => {
    const schema = await loadSchema();
    const first = emitMigrations(schema);
    const again = emitMigrations(schema, first.nextState);
    expect(again.files).toEqual({});
    expect(again.nextState).toBeUndefined();
  });

  it("changed schema: appends the NEXT version instead of rewriting v0001", async () => {
    const schema = await loadSchema();
    const first = emitMigrations(schema);
    const grown: typeof schema = {
      ...schema,
      hypertables: [...schema.hypertables, { table: "EventLog", column: "at", chunkInterval: "1 day" }],
    };
    const second = emitMigrations(grown, first.nextState);
    // v0001 is never touched again; only the extension file (byte-identical) and v0002 appear.
    expect(Object.keys(second.files).sort()).toEqual([`${EXTENSION_MIGRATION}/migration.sql`, V2]);
    expect(second.files[V2]).toContain(`'"EventLog"'`);
    // The new version re-asserts the FULL state (idempotent), not just the delta.
    expect(second.files[V2]).toContain(`'"SensorReading"'`);
    expect(second.nextState?.sequence).toBe(2);
  });

  it("matches the reset-safe extension SQL", async () => {
    const { files } = emitMigrations(await loadSchema());
    expect(files[`${EXTENSION_MIGRATION}/migration.sql`]).toMatchInlineSnapshot(`
      "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.
      -- TimescaleDB extension setup. Standalone & leading so it runs before any table or
      -- hypertable DDL (CLAUDE.md constraint 1).
      CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
      "
    `);
  });

  it("matches the guarded reset-safe objects SQL (hypertable then cagg, no casts)", async () => {
    const { files } = emitMigrations(await loadSchema());
    const objects = files[V1]!;
    expect(objects).not.toContain("::regclass");
    expect(objects).not.toContain("::name");
    expect(objects.indexOf("create_hypertable")).toBeLessThan(objects.indexOf("CREATE MATERIALIZED VIEW"));
    expect(objects).toMatchInlineSnapshot(`
      "-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.
      -- TimescaleDB objects, state v1. Sorts last so the tables Prisma created in its own
      -- migrations already exist. Never rewritten: a schema change appends the next version instead.
      -- Every block is idempotent and guarded (skips if its table was dropped later), so a full
      -- \`migrate reset\` replay of v1..v1 converges on exactly this state (constraint 3).

      -- Hypertable: SensorReading
      DO $$ BEGIN
        IF to_regclass('"SensorReading"') IS NULL THEN RAISE WARNING 'prisma-extension-timescaledb: relation % does not exist; skipping (table dropped by a later migration, or its CREATE TABLE migration is missing)', '"SensorReading"'; RETURN; END IF;
        PERFORM create_hypertable(
          '"SensorReading"',
          by_range('time', INTERVAL '1 day'),
          if_not_exists => TRUE,
          migrate_data  => TRUE
        );
      END $$;

      -- Continuous aggregate: SensorHourly
      DO $$ BEGIN
        IF to_regclass('"SensorReading"') IS NULL THEN RAISE WARNING 'prisma-extension-timescaledb: relation % does not exist; skipping (table dropped by a later migration, or its CREATE TABLE migration is missing)', '"SensorReading"'; RETURN; END IF;
        CREATE MATERIALIZED VIEW IF NOT EXISTS "SensorHourly"
          WITH (timescaledb.continuous) AS
        SELECT
          time_bucket('1 hour', "time") AS "bucket",
          "deviceId" AS "deviceId",
          avg("temperature") AS "avgTemp",
          max("temperature") AS "maxTemp"
        FROM "SensorReading"
        GROUP BY time_bucket('1 hour', "time"), "deviceId"
        WITH NO DATA;
        PERFORM add_continuous_aggregate_policy('"SensorHourly"',
          start_offset      => INTERVAL '1 month',
          end_offset        => INTERVAL '1 hour',
          schedule_interval => INTERVAL '1 hour',
          if_not_exists     => TRUE
        );
      END $$;
      "
    `);
  });

  const withAnnotations = async (annotations: string, fields = "") => {
    const dmmf = await getDMMF({
      datamodel: `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}

${annotations}
model SensorReading {
  time     DateTime
  deviceId Int
${fields}  @@id([deviceId, time])
}
`,
    });
    return extractTimescaleSchema(dmmf);
  };

  it("emits the guarded retention policy after its hypertable", async () => {
    const schema = await withAnnotations(
      `/// @timescale.hypertable(column: "time", chunkInterval: "1 day")\n/// @timescale.retention(dropAfter: "30 days")`,
    );
    const objects = emitMigrations(schema).files[V1]!;
    expect(objects).toContain(
      `PERFORM add_retention_policy('"SensorReading"', drop_after => INTERVAL '30 days', if_not_exists => TRUE);`,
    );
    expect(objects).toContain(`IF to_regclass('"SensorReading"') IS NULL THEN RAISE WARNING`);
    expect(objects).not.toContain("::regclass");
    expect(objects.indexOf("create_hypertable")).toBeLessThan(objects.indexOf("add_retention_policy"));
  });

  it("emits the guarded compression policy (columnstore + CALL) after its hypertable", async () => {
    const schema = await withAnnotations(
      `/// @timescale.hypertable(column: "time", chunkInterval: "1 day")\n/// @timescale.compression(after: "7 days", segmentBy: "deviceId", orderBy: "time DESC")`,
    );
    const objects = emitMigrations(schema).files[V1]!;
    expect(objects).toContain("timescaledb.enable_columnstore = true");
    expect(objects).toContain(`timescaledb.segmentby = '"deviceId"'`);
    expect(objects).toContain(`timescaledb.orderby = '"time" DESC'`);
    expect(objects).toContain(
      `CALL add_columnstore_policy('"SensorReading"', after => INTERVAL '7 days', if_not_exists => TRUE);`,
    );
    expect(objects).not.toContain("::regclass");
    expect(objects.indexOf("create_hypertable")).toBeLessThan(objects.indexOf("add_columnstore_policy"));
  });

  it("emits guarded chunk skipping (DO block + enable_chunk_skipping) after its hypertable", async () => {
    const schema = await withAnnotations(
      `/// @timescale.hypertable(column: "time", chunkInterval: "1 day", chunkSkipping: "eventId")`,
      "  eventId  BigInt\n",
    );
    const objects = emitMigrations(schema).files[V1]!;
    expect(objects).toContain("SET LOCAL timescaledb.enable_chunk_skipping = on;");
    expect(objects).toContain(`PERFORM enable_chunk_skipping('"SensorReading"', 'eventId', if_not_exists => TRUE);`);
    expect(objects).not.toContain("::regclass");
    expect(objects.indexOf("create_hypertable")).toBeLessThan(objects.indexOf("enable_chunk_skipping"));
  });

  it("orders a hierarchical cagg after the source cagg it depends on (topological, not alphabetical)", async () => {
    const dmmf = await getDMMF({
      datamodel: `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}

/// @timescale.hypertable(column: "time", chunkInterval: "1 day")
model SensorReading {
  time        DateTime
  temperature Float
  @@id([time])
}

/// @timescale.continuousAggregate(source: "Zinner", bucket: "1 day", timeColumn: "bucket")
view Aouter {
  bucket  DateTime /// @timescale.bucket
  avgTemp Float    /// @timescale.aggregate(fn: "avg", column: "avgTemp")
  @@unique([bucket])
}

/// @timescale.continuousAggregate(source: "SensorReading", bucket: "1 hour", timeColumn: "time")
view Zinner {
  bucket  DateTime /// @timescale.bucket
  avgTemp Float    /// @timescale.aggregate(fn: "avg", column: "temperature")
  @@unique([bucket])
}
`,
    });
    const objects = emitMigrations(extractTimescaleSchema(dmmf)).files[V1]!;
    const inner = objects.indexOf(`CREATE MATERIALIZED VIEW IF NOT EXISTS "Zinner"`);
    const outer = objects.indexOf(`CREATE MATERIALIZED VIEW IF NOT EXISTS "Aouter"`);
    expect(inner).toBeGreaterThanOrEqual(0);
    expect(outer).toBeGreaterThanOrEqual(0);
    expect(inner).toBeLessThan(outer);
  });

  it("a removed cagg is dropped (DROP MATERIALIZED VIEW, constraint 4) in the next version", async () => {
    const schema = await loadSchema();
    const first = emitMigrations(schema);
    const withoutCagg: typeof schema = { ...schema, continuousAggregates: [] };
    const second = emitMigrations(withoutCagg, first.nextState);
    const v2 = second.files[V2]!;
    expect(v2).toContain(`DROP MATERIALIZED VIEW IF EXISTS "SensorHourly";`);
    expect(v2).not.toContain("DROP VIEW ");
    // Removal comes before the re-asserted creates.
    expect(v2.indexOf("DROP MATERIALIZED VIEW")).toBeLessThan(v2.indexOf("create_hypertable"));
  });

  it("a removed retention/compression policy is removed in the next version; hypertable removal warns", async () => {
    const base = await withAnnotations(
      `/// @timescale.hypertable(column: "time", chunkInterval: "1 day")\n/// @timescale.retention(dropAfter: "30 days")\n/// @timescale.compression(after: "7 days")`,
    );
    const first = emitMigrations(base);
    const bare = await withAnnotations(`/// @timescale.hypertable(column: "time", chunkInterval: "1 day")`);
    const second = emitMigrations(bare, first.nextState);
    const v2 = second.files[V2]!;
    expect(v2).toContain(`PERFORM remove_retention_policy('"SensorReading"', if_exists => TRUE);`);
    expect(v2).toContain(`CALL remove_columnstore_policy('"SensorReading"', if_exists => TRUE);`);

    // Removing the hypertable annotation entirely: policies removed, un-hypertable impossible.
    const gone = extractTimescaleSchema(
      await getDMMF({
        datamodel: `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}
model Unrelated {
  id Int @id
}
`,
      }),
    );
    const third = emitMigrations(gone, second.nextState);
    const v3 = third.files[`${objectsMigrationName(3)}/migration.sql`]!;
    expect(v3).toContain("TimescaleDB cannot convert a hypertable back");
    expect(third.nextState?.sequence).toBe(3);
  });

  it("relation-only changes do not spawn a new migration (state excludes relations)", async () => {
    const schema = await loadSchema();
    const first = emitMigrations(schema);
    const withRelations: typeof schema = {
      ...schema,
      hypertables: schema.hypertables.map((h) => ({
        ...h,
        relations: [{ field: "x", table: "X", list: false, on: [{ related: "id", outer: "xId" }] }],
      })),
      relationsByModel: { X: [{ field: "readings", table: "SensorReading", list: true, on: [{ related: "xId", outer: "id" }] }] },
    };
    const again = emitMigrations(withRelations, first.nextState);
    expect(again.files).toEqual({});
  });

  it("state round-trips through JSON (what the generator persists and reloads)", async () => {
    const schema = await loadSchema();
    const first = emitMigrations(schema);
    const reloaded = JSON.parse(JSON.stringify(first.nextState)) as GeneratorState;
    expect(emitMigrations(schema, reloaded).files).toEqual({});
  });
});

describe("emitTypes", () => {
  it("emits a type module that type-checks under strict mode", async () => {
    const source = emitTypes(await loadSchema())["index.ts"]!;
    expect(typeCheck(source)).toEqual([]);
  });

  it("matches the generated type module", async () => {
    const source = emitTypes(await loadSchema())["index.ts"]!;
    expect(source).toMatchInlineSnapshot(`
      "// AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.

      /**
       * Branded time type for hypertable partition columns. Range-bounded query helpers can require
       * this so callers can't forget the time bound (SPEC §3).
       */
      export type HypertableTime = Date & { readonly __timescaleTime: unique symbol };

      /** Runtime description of every hypertable and continuous aggregate in the schema. */
      export const registry = {
        "hypertables": [
          {
            "table": "SensorReading",
            "column": "time",
            "chunkInterval": "1 day"
          }
        ],
        "continuousAggregates": [
          {
            "name": "SensorHourly",
            "source": "SensorReading",
            "bucket": "1 hour",
            "timeColumn": "time",
            "bucketColumn": "bucket",
            "groupBy": [
              {
                "source": "deviceId",
                "output": "deviceId"
              }
            ],
            "aggregates": [
              {
                "name": "avgTemp",
                "fn": "avg",
                "column": "temperature"
              },
              {
                "name": "maxTemp",
                "fn": "max",
                "column": "temperature"
              }
            ],
            "refresh": {
              "startOffset": "1 month",
              "endOffset": "1 hour",
              "scheduleInterval": "1 hour"
            }
          }
        ]
      } as const;

      /** The shape of {@link registry}, for typing the client extension. */
      export type TimescaleRegistry = typeof registry;
      "
    `);
  });

  it("emits relationsByModel for related (non-hypertable) models, and it still type-checks as `as const`", async () => {
    const dmmf = await getDMMF({
      datamodel: `
generator client {
  provider = "prisma-client"
  output = "../generated/prisma"
  previewFeatures = ["views"]
}
datasource db {
  provider = "postgresql"
}

/// @timescale.hypertable(column: "time", chunkInterval: "1 day")
model Reading {
  time     DateTime
  id       Int
  deviceId Int?
  device   Device? @relation(fields: [deviceId], references: [id])
  @@id([id, time])
}
model Device {
  id       Int       @id
  active   Boolean
  readings Reading[]
}
`,
    });
    const source = emitTypes(extractTimescaleSchema(dmmf))["index.ts"]!;
    expect(source).toContain(`"relationsByModel"`);
    expect(source).toContain(`"targetModel": "Reading"`); // Device.readings -> Reading, for nesting
    expect(typeCheck(source)).toEqual([]);
  });
});
